### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by klezm** [microsoft/Reference-Guide-For-Quantum-Computing-A-Microsoft-Garage-Project#8]
in [1-Basic_Quantum_Concepts/1-States.ipynb](https://github.com/microsoft/Reference-Guide-For-Quantum-Computing-A-Microsoft-Garage-Project/blob/7ad48da242dfc097ce9048168283b0367e3b1eb3/1-Basic_Quantum_Concepts/1-States.ipynb) these 3 links are broken. The URL seems to be cut off.
https://github.com/microsoft/Reference-Guide-For-Quantum-Computing-A-Microsoft-Garage-Project/blob/7ad48da242dfc097ce9048168283b0367e3b1eb3/1-Basic_Quantum_Concepts/1-States.ipynb#L175-L179

at least 2 Quirk links are not working:
https://github.com/microsoft/Reference-Guide-For-Quantum-Computing-A-Microsoft-Garage-Project/blob/7ad48da242dfc097ce9048168283b0367e3b1eb3/1-Basic_Quantum_Concepts/3-Entanglement.ipynb#L179
https://github.com/microsoft/Reference-Guide-For-Quantum-Computing-A-Microsoft-Garage-Project/blob/7ad48da242dfc097ce9048168283b0367e3b1eb3/1-Basic_Quantum_Concepts/3-Entanglement.ipynb#L179

In both cases the URL is cut off.

in [1-Basic_Quantum_Concepts/6-CHSH_Game.ipynb](https://github.com/microsoft/Reference-Guide-For-Quantum-Computing-A-Microsoft-Garage-Project/blob/main/1-Basic_Quantum_Concepts/6-CHSH_Game.ipynb) the Quirk link works fine.

**Comment by benjamintokgoez** [comment]
Thank you for this issue! We'll take a look at the broken links as soon as possible.

**Comment by klezm** [comment]
I just saw, that I posted the same link twice and just updated the original issue.
The Issue in the teleportation notebook still exists (and I didn't check if there are more broken quirk links, maybe you can implement a unit test for that?)

Also the (arxiv) links in the first notebook still don't work.

PS: thanks for fixing the first quirk link!!
